server:
  port: 8080
  servlet:
      session:
          timeout: 3600s

spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://39.107.91.212:3306/srm?useUnicode=true&characterEncoding=UTF-8&useReadAheadInput=false&useUnbufferedInput=false&useSSL=false
      username: root
      password: 123456
      initialSize : 5
      minIdle : 5
      # 配置获取连接等待超时的时间
      maxActive : 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      maxWait : 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis : 30000